In [1]:
import numpy as np

def import_data_from_csv(predictions_file, actual_file):
    # Importer les prédictions à partir d'un fichier CSV
    with open(predictions_file, newline='') as csvfile:
        predictions = np.loadtxt(predictions_file, delimiter=',', dtype=float)

    # Importer les valeurs réelles à partir d'un fichier CSV
    with open(actual_file, newline='') as csvfile:
        actual = np.loadtxt(actual_file, delimiter=',', dtype=int)

    return predictions, actual

def print_data(predictions, actual, num_rows=5):
    # Afficher les cinq premières lignes des prédictions
    print("Cinq premières lignes des prédictions :")
    for row in predictions[:num_rows]:
        print(row)

    # Afficher les cinq premières lignes des valeurs réelles
    print("\nCinq premières lignes des valeurs réelles :")
    for row in actual[:num_rows]:
        print(row)

# Utiliser la fonction pour importer et afficher les données
predictions, actual = import_data_from_csv('y_pred_NN_tanh_6-4.csv', 'y_test.csv')
print_data(predictions, actual)

    



Cinq premières lignes des prédictions :
[0.64492953 0.00141837 0.26305687 0.32325251]
[0.02438738 0.93292826 0.07030108 0.03982514]
[0.00888338 0.1732657  0.72770764 0.10411615]
[0.65897928 0.02591195 0.03877026 0.15991084]
[0.8671595  0.02220564 0.00918483 0.14843525]

Cinq premières lignes des valeurs réelles :
3
1
2
0
0


In [2]:
# Afficher les cinq premières lignes des prédictions et des valeurs réelles
print("Cinq premières lignes des prédictions :")
for row in predictions[:5]:
    print(row)

print("\nCinq premières lignes des valeurs réelles :")
for row in actual[:5]:
    print(row)

Cinq premières lignes des prédictions :
[0.64492953 0.00141837 0.26305687 0.32325251]
[0.02438738 0.93292826 0.07030108 0.03982514]
[0.00888338 0.1732657  0.72770764 0.10411615]
[0.65897928 0.02591195 0.03877026 0.15991084]
[0.8671595  0.02220564 0.00918483 0.14843525]

Cinq premières lignes des valeurs réelles :
3
1
2
0
0


In [3]:
def translate_predictions(predictions):
    # Utiliser argmax pour trouver l'indice de la valeur maximale dans chaque ligne
    max_indices = np.argmax(predictions, axis=1)
    
    # Convertir les indices en une matrice numpy avec une seule colonne
    translated_predictions_matrix = max_indices.reshape(-1, 1)
    
    return translated_predictions_matrix

# Utiliser la fonction pour traduire les prédictions
translated_predictions_matrix = translate_predictions(predictions)



def print_actual(actual):
    print("Cinq premières valeurs de la variable réelle :")
    print(actual[:5])



In [4]:
def calculate_confusion_matrix(actual, predicted, num_classes=4):
    # Créer une matrice de confusion vide
    confusion_matrix = np.zeros((num_classes, num_classes), dtype=int)

    # Remplir la matrice de confusion
    for true, pred in zip(actual, predicted):
        confusion_matrix[true, pred] += 1

    return confusion_matrix


On print les matrices de confusion

In [5]:



predictions1, actual1 = import_data_from_csv('y_pred_NN_relu_6-4.csv', 'y_test.csv')
predictions1 = translate_predictions(predictions)
matrix1 = calculate_confusion_matrix(actual1, predictions1, num_classes=4)
print("Matrice de confusion pour NN Relu 6-4")
print(matrix1)

predictions2, actual1 = import_data_from_csv('y_pred_NN_relu_10-8-4.csv', 'y_test.csv')
predictions2 = translate_predictions(predictions2)
matrix2 = calculate_confusion_matrix(actual1, predictions2, num_classes=4)
print("Matrice de confusion pour NN Relu 10-8-4")
print(matrix2)

predictions3, actual1 = import_data_from_csv('y_pred_NN_relu_10-8-6.csv', 'y_test.csv')
predictions3 = translate_predictions(predictions3)
matrix3 = calculate_confusion_matrix(actual1, predictions3, num_classes=4)
print("Matrice de confusion pour NN Relu 10-8-6")
print(matrix3)

predictions4, actual1 = import_data_from_csv('y_pred_NN_tanh_6-4.csv', 'y_test.csv')
predictions4 = translate_predictions(predictions4)
matrix4 = calculate_confusion_matrix(actual1, predictions4, num_classes=4)
print("Matrice de confusion pour NN tanh 6-4")
print(matrix4)

predictions5, actual1 = import_data_from_csv('y_pred_NN_tanh_10-8-4.csv', 'y_test.csv')
predictions5 = translate_predictions(predictions5)
matrix5 = calculate_confusion_matrix(actual1, predictions5, num_classes=4)
print("Matrice de confusion pour NN tanh 10-8-4")
print(matrix5)

predictions6, actual1 = import_data_from_csv('y_pred_NN_tanh_10-8-6.csv', 'y_test.csv')
predictions6 = translate_predictions(predictions6)
matrix6 = calculate_confusion_matrix(actual1, predictions6, num_classes=4)
print("Matrice de confusion pour NN tanh 10-8-6")
print(matrix6)




Matrice de confusion pour NN Relu 6-4
[[139   9   8   0]
 [  1 165   0   0]
 [  4   6  79   0]
 [ 21  10  18   0]]
Matrice de confusion pour NN Relu 10-8-4
[[136   8   5   7]
 [  0 163   2   1]
 [  2   4  81   2]
 [  2  12   9  26]]
Matrice de confusion pour NN Relu 10-8-6
[[135   9   5   7]
 [  0 155   4   7]
 [  2   3  80   4]
 [  2   5  10  32]]
Matrice de confusion pour NN tanh 6-4
[[139   9   8   0]
 [  1 165   0   0]
 [  4   6  79   0]
 [ 21  10  18   0]]
Matrice de confusion pour NN tanh 10-8-4
[[142   9   5   0]
 [  0 163   3   0]
 [  2   3  84   0]
 [ 13  13  23   0]]
Matrice de confusion pour NN tanh 10-8-6
[[144   5   1   6]
 [  0 162   2   2]
 [  3   4  81   1]
 [  2  10   5  32]]


In [6]:

def calculate_metrics(confusion_matrix):
    # Calculer les valeurs de TP, TN, FP, FN
    TP = np.diag(confusion_matrix)
    FP = np.sum(confusion_matrix, axis=0) - TP
    FN = np.sum(confusion_matrix, axis=1) - TP
    TN = np.sum(confusion_matrix) - (TP + FP + FN)

    # Calculer l'exactitude (accuracy)
    accuracy = (TP + TN) / np.sum(confusion_matrix)

    # Calculer la précision (precision)
    precision = TP / (TP + FP)

    # Calculer le rappel (recall)
    recall = TP / (TP + FN)

    # Calculer le score F1
    f1_score = 2 * (precision * recall) / (precision + recall)
        # Afficher les métriques
    print("Les classes :           Class0      Class1     Class2     Class3")
    print("Exactitude (Accuracy) :", accuracy)
    print("Précision (Precision) :", precision)
    print("Rappel (Recall) :      ", recall)
    print("Score F1 (F1 Score) :  ", f1_score)

    return accuracy, precision, recall, f1_score

# Calculer les métriques pour chaque matrice de confusion
print("Métriques pour NN Relu 6-4 :")
metrics1 = calculate_metrics(matrix1)
print("\nMétriques pour NN Relu 10-8-4 :")
metrics2 = calculate_metrics(matrix2)
print("\nMétriques pour NN Relu 10-8-6 :")
metrics3 = calculate_metrics(matrix3)
print("\nMétriques pour NN tanh 6-4 :")
metrics4 = calculate_metrics(matrix4)
print("\nMétriques pour NN tanh 10-8-4 :")
metrics5 = calculate_metrics(matrix5)
print("\nMétriques pour NN tanh 10-8-6 :")
metrics6 = calculate_metrics(matrix6)

Métriques pour NN Relu 6-4 :
Les classes :           Class0      Class1     Class2     Class3
Exactitude (Accuracy) : [0.90652174 0.94347826 0.92173913 0.89347826]
Précision (Precision) : [0.84242424 0.86842105 0.75238095        nan]
Rappel (Recall) :       [0.89102564 0.9939759  0.88764045 0.        ]
Score F1 (F1 Score) :   [0.86604361 0.92696629 0.81443299        nan]

Métriques pour NN Relu 10-8-4 :
Les classes :           Class0      Class1     Class2     Class3
Exactitude (Accuracy) : [0.94782609 0.94130435 0.94782609 0.92826087]
Précision (Precision) : [0.97142857 0.87165775 0.83505155 0.72222222]
Rappel (Recall) :       [0.87179487 0.98192771 0.91011236 0.53061224]
Score F1 (F1 Score) :   [0.91891892 0.92351275 0.87096774 0.61176471]

Métriques pour NN Relu 10-8-6 :
Les classes :           Class0      Class1     Class2     Class3
Exactitude (Accuracy) : [0.94565217 0.93913043 0.93913043 0.92391304]
Précision (Precision) : [0.97122302 0.90116279 0.80808081 0.64      ]
Rappel (Re

C:\Users\musab\AppData\Local\Temp\ipykernel_27596\3762503073.py:12: RuntimeWarning: invalid value encountered in divide
  precision = TP / (TP + FP)
