In [7]:
import numpy as np
import pandas as pd

def import_data_from_csv(predictions_file, actual_file):
    # Importer les prédictions à partir d'un fichier CSV
    predictions = np.loadtxt(predictions_file, delimiter=',', dtype=float)

    # Importer les valeurs réelles à partir d'un fichier CSV
    actual = np.loadtxt(actual_file, delimiter=',', dtype=int)

    return predictions, actual

def print_data(predictions, actual, num_rows=5):
    # Afficher les cinq premières lignes des prédictions
    print("Cinq premières lignes des prédictions :")
    print(predictions[:num_rows])

    # Afficher les cinq premières lignes des valeurs réelles
    print("\nCinq premières lignes des valeurs réelles :")
    print(actual[:num_rows])

# Utiliser la fonction pour importer et afficher les données
predictions, actual = import_data_from_csv('y_pred_DT4.csv', 'y_test.csv')
print_data(predictions, actual)


Cinq premières lignes des prédictions :
[2. 1. 0. 1. 0.]

Cinq premières lignes des valeurs réelles :
[3 1 2 0 0]


In [8]:

def reshape_to_single_column(data):
    # Convertir les valeurs en entiers et redimensionner en une seule colonne
    reshaped_data = data.astype(int).reshape(-1, 1)
    return reshaped_data

# Exemple d'utilisation
predictions = np.array([2., 1., 0., 1., 0.])
actual = np.array([3, 1, 2, 0, 0])

predictions_single_column = reshape_to_single_column(predictions)
actual_single_column = reshape_to_single_column(actual)
print("Prédictions (une seule colonne) :")
print(predictions_single_column)
print("\nValeurs réelles (une seule colonne) :")
print(actual_single_column)


Prédictions (une seule colonne) :
[[2]
 [1]
 [0]
 [1]
 [0]]

Valeurs réelles (une seule colonne) :
[[3]
 [1]
 [2]
 [0]
 [0]]


In [9]:
def calculate_confusion_matrix(actual, predicted, num_classes=4):
    # Créer une matrice de confusion vide
    confusion_matrix = np.zeros((num_classes, num_classes), dtype=int)

    # Remplir la matrice de confusion
    for true, pred in zip(actual, predicted):
        confusion_matrix[true, pred] += 1

    return confusion_matrix

In [10]:
predictions1, actual = import_data_from_csv('y_pred_DT4.csv', 'y_test.csv')
actual = reshape_to_single_column(actual)
predictions1 = reshape_to_single_column(predictions1)
matrix1 = calculate_confusion_matrix(actual, predictions1, num_classes=4)
print("Matrice de confusion pour y-pred-DT4")
print(matrix1)


predictions2, actual = import_data_from_csv('y_pred_DT5.csv', 'y_test.csv')
actual = reshape_to_single_column(actual)
predictions2 = reshape_to_single_column(predictions2)
matrix2 = calculate_confusion_matrix(actual, predictions2, num_classes=4)
print("Matrice de confusion pour y-pred-DT5")
print(matrix2)

predictions3, actual = import_data_from_csv('y_pred_DT6.csv', 'y_test.csv')
actual = reshape_to_single_column(actual)
predictions3 = reshape_to_single_column(predictions3)
matrix3 = calculate_confusion_matrix(actual, predictions3, num_classes=4)
print("Matrice de confusion pour y-pred-DT6")
print(matrix3)

Matrice de confusion pour y-pred-DT4
[[130  19   6   1]
 [ 15 147   2   2]
 [ 25  20  44   0]
 [ 12   8  23   6]]
Matrice de confusion pour y-pred-DT5
[[126  14  10   6]
 [ 12 140   9   5]
 [ 12   5  67   5]
 [  7   5  16  21]]
Matrice de confusion pour y-pred-DT6
[[130  14  10   2]
 [  9 147   3   7]
 [  9   7  71   2]
 [  5   7  11  26]]


In [11]:
def calculate_metrics(confusion_matrix):
    # Calculer les valeurs de TP, TN, FP, FN
    TP = np.diag(confusion_matrix)
    FP = np.sum(confusion_matrix, axis=0) - TP
    FN = np.sum(confusion_matrix, axis=1) - TP
    TN = np.sum(confusion_matrix) - (TP + FP + FN)

    # Calculer l'exactitude (accuracy)
    accuracy = (TP + TN) / np.sum(confusion_matrix)

    # Calculer la précision (precision)
    precision = TP / (TP + FP)

    # Calculer le rappel (recall)
    recall = TP / (TP + FN)

    # Calculer le score F1
    f1_score = 2 * (precision * recall) / (precision + recall)
        # Afficher les métriques
    print("Les classes :           Class0      Class1     Class2     Class3")
    print("Exactitude (Accuracy) :", accuracy)
    print("Précision (Precision) :", precision)
    print("Rappel (Recall) :      ", recall)
    print("Score F1 (F1 Score) :  ", f1_score)

    return accuracy, precision, recall, f1_score


# Calculer les métriques pour chaque matrice de confusion
print("Métriques pour y-pred-DT4 :")
metrics1 = calculate_metrics(matrix1)
print("\nMétriques pour y-pred-DT-5 :")
metrics2 = calculate_metrics(matrix2)
print("\nMétriques pour y-pred-DT6 :")
metrics3 = calculate_metrics(matrix3)

Métriques pour y-pred-DT4 :
Les classes :           Class0      Class1     Class2     Class3
Exactitude (Accuracy) : [0.83043478 0.85652174 0.83478261 0.9       ]
Précision (Precision) : [0.71428571 0.75773196 0.58666667 0.66666667]
Rappel (Recall) :       [0.83333333 0.88554217 0.49438202 0.12244898]
Score F1 (F1 Score) :   [0.76923077 0.81666667 0.53658537 0.20689655]

Métriques pour y-pred-DT-5 :
Les classes :           Class0      Class1     Class2     Class3
Exactitude (Accuracy) : [0.8673913  0.89130435 0.87608696 0.90434783]
Précision (Precision) : [0.80254777 0.85365854 0.65686275 0.56756757]
Rappel (Recall) :       [0.80769231 0.84337349 0.75280899 0.42857143]
Score F1 (F1 Score) :   [0.80511182 0.84848485 0.70157068 0.48837209]

Métriques pour y-pred-DT6 :
Les classes :           Class0      Class1     Class2     Class3
Exactitude (Accuracy) : [0.89347826 0.89782609 0.90869565 0.92608696]
Précision (Precision) : [0.8496732  0.84       0.74736842 0.7027027 ]
Rappel (Recall) : 